# Generated by Django 4.0.3 on 2022-07-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс. длинна 90 символов', max_length=90, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс. длинна 90 символов', max_length=90, verbose_name='Цвета')),
                ('name_eng', models.CharField(help_text='Макс. длинна 90 символов', max_length=90, verbose_name='Цвет на английском')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='', verbose_name='Картинка 1')),
                ('image_2', models.ImageField(upload_to='', verbose_name='Картинка 2')),
                ('name', models.CharField(help_text='Макс. длинна 90 символов', max_length=90, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('cost_sale', models.IntegerField(verbose_name='Цена со скидкой')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.color', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.product', verbose_name='Базовый товар')),
            ],
            options={
                'verbose_name': 'Вариация',
                'verbose_name_plural': 'Вариации',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс. длинна 90 символов', max_length=90, verbose_name='Серия')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
