# Generated by Django 4.0.3 on 2022-07-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='grope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_app.group', verbose_name='Товарная группа'),
            preserve_default=False,
        ),
    ]
