# Generated by Django 4.0.3 on 2022-07-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_category_grope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='grope',
            new_name='group',
        ),
    ]
