# Generated by Django 4.0.3 on 2022-07-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_rename_grope_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='media_default/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
